version: '3'
services:
  hyperf:
    container_name: hyperf
    image: hyperf/hyperf:8.0-alpine-v3.15-swoole
    volumes:
      - ./:/data/project/hyperf-skeleton
    ports:
      - "9501:9501"
    working_dir: /data/project/hyperf-skeleton
    command: /bin/sh
    privileged: true
    user: root
    networks:
      - hyperf-network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: petcare
      DB_USERNAME: petcare
      DB_PASSWORD: petcare

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: teste
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - hyperf-network

networks:
  hyperf-network:
