services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf/hyperf:8.1-alpine-v3.13-swoole
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    privileged: true  # Verifique se realmente precisa de privilégios elevados
    user: root  # Isso é necessário para seu caso de uso?
    networks:
      - hyperf-network
    environment:
      APP_ENV: dev
      SCAN_CACHEABLE: "true"
      DB_CONNECTION: mysql
      DB_HOST: hyperf-skeleton-mariadb
      DB_PORT: 3306
      DB_DATABASE: petcare
      DB_USERNAME: root
      DB_PASSWORD: secret

  hyperf-skeleton-mariadb:
    container_name: hyperf-skeleton-mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - hyperf-network
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "petcare"

networks:
  hyperf-network:
